name: Deploy to Cocoapods Trunk

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Cocoapods
      run: gem install cocoapods
    
    - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.10
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
